#Hopswork Server Config File
server:
  url: "http://bbc6.sics.se"
  port: 8080
  path: "/hopsworks-api/api"
user:
  email: "admin@kth.se"
  password: "admin"
api:
  fileUpload: "/project/{id}/dataset/{fileName}"
  auth: "/auth/login"
